# Generated by Django 5.0.1 on 2024-01-29 10:10

import accounts.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='investigator',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('admin_investigator_objects', accounts.models.AdminInvestigatorManager()),
                ('investigator_objects', accounts.models.InvestigatorManager()),
            ],
        ),
        migrations.AddField(
            model_name='investigator',
            name='user_type',
            field=models.CharField(choices=[('INV', 'Investigator'), ('ADM', 'Admin Investigator')], default='INV', max_length=3),
        ),
    ]
