# Generated by Django 5.0.1 on 2024-01-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_investigator_managers_investigator_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigator',
            old_name='user_type',
            new_name='investigator_type',
        ),
    ]
