# Generated by Django 5.0.1 on 2024-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_type_investigator_investigator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
