# Generated by Django 5.0.1 on 2024-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalprofile',
            name='description',
        ),
        migrations.AlterField(
            model_name='criminalprofile',
            name='height',
            field=models.PositiveIntegerField(help_text='Height in centimeters'),
        ),
    ]
