# Generated by Django 5.0.1 on 2024-02-06 01:33

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_remove_criminalprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('device_model', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Associated Devices',
            },
        ),
        migrations.CreateModel(
            name='AssociatedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', django_countries.fields.CountryField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Associated IPs',
            },
        ),
        migrations.CreateModel(
            name='CyberCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('d_o_b', models.DateField(help_text='Date of Birth')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('last_known_location', django_countries.fields.CountryField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Criminal Profiles',
            },
        ),
        migrations.CreateModel(
            name='KnownPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Known Phrases',
            },
        ),
        migrations.RemoveField(
            model_name='criminalprofile',
            name='known_phrases',
        ),
        migrations.RemoveField(
            model_name='criminalprofile',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='criminalprofile',
            name='tactics',
        ),
        migrations.RemoveField(
            model_name='criminalprofile',
            name='techniques',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='name',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tactics',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tactics',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PsychologicalProfile',
            fields=[
                ('cyber_criminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiler.cybercriminal')),
                ('aggression_level', models.IntegerField(help_text='Aggression level on a scale of 1-10')),
                ('risk_taking_level', models.IntegerField(help_text='Risk-taking level on a scale of 1-10')),
            ],
            options={
                'verbose_name_plural': 'Psychological Profiles',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cyber_criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.cybercriminal')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='PhysicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(help_text='Height in centimeters')),
                ('weight', models.PositiveIntegerField(help_text='Weight in kilograms')),
                ('hair_color', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=255)),
                ('cyber_criminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiler.cybercriminal')),
            ],
            options={
                'verbose_name_plural': 'Physical Profiles',
            },
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='physical_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiler.physicalprofile'),
        ),
        migrations.CreateModel(
            name='PreviousConviction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conviction', models.TextField()),
                ('date', models.DateField()),
                ('cyber_criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.cybercriminal')),
            ],
            options={
                'verbose_name_plural': 'Previous Convictions',
            },
        ),
        migrations.CreateModel(
            name='TechnicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField(help_text='Manifesto')),
                ('associated_devices', models.ManyToManyField(related_name='criminal_profiles', to='profiler.associateddevice')),
                ('associated_ips', models.ManyToManyField(related_name='criminal_profiles', to='profiler.associatedip')),
                ('cyber_criminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiler.cybercriminal')),
                ('hacker_classification', models.ManyToManyField(related_name='technical_profiles', to='profiler.technique')),
                ('known_devices', models.ManyToManyField(related_name='technical_profiles', to='profiler.associateddevice')),
                ('known_ips', models.ManyToManyField(related_name='technical_profiles', to='profiler.associatedip')),
                ('known_phrases', models.ManyToManyField(related_name='criminal_profiles', to='profiler.knownphrase')),
                ('procedures', models.ManyToManyField(related_name='criminal_profiles', to='profiler.procedure')),
                ('tactics', models.ManyToManyField(related_name='criminal_profiles', to='profiler.tactics')),
                ('techniques', models.ManyToManyField(related_name='criminal_profiles', to='profiler.technique')),
            ],
            options={
                'verbose_name_plural': 'Technical Profiles',
            },
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='technical_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiler.technicalprofile'),
        ),
        migrations.DeleteModel(
            name='KnownPhrases',
        ),
        migrations.DeleteModel(
            name='CriminalProfile',
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='psychological_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiler.psychologicalprofile'),
        ),
    ]
