# Generated by Django 5.0.1 on 2024-02-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_associateddevice_associatedip_cybercriminal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cybercriminal',
            options={'verbose_name_plural': 'Cyber Criminals'},
        ),
    ]
