# Generated by Django 5.0.1 on 2024-02-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0004_alter_cybercriminal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cybercriminal',
            name='physical_profile',
        ),
        migrations.RemoveField(
            model_name='cybercriminal',
            name='psychological_profile',
        ),
        migrations.RemoveField(
            model_name='cybercriminal',
            name='technical_profile',
        ),
    ]
