# Generated by Django 5.0.1 on 2024-02-06 01:37

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0005_remove_cybercriminal_physical_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercriminal',
            name='last_known_location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
