# Generated by Django 5.0.1 on 2024-02-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0008_remove_technicalprofile_hacker_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalprofile',
            name='manifesto',
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='associated_devices',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.associateddevice'),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='associated_ips',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.associatedip'),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='known_phrases',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.knownphrase'),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.procedure'),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='tactics',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.tactics'),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.technique'),
        ),
    ]
