# Generated by Django 5.0.1 on 2024-02-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0009_remove_technicalprofile_manifesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalprofile',
            name='known_devices',
            field=models.ManyToManyField(blank=True, related_name='technical_profiles', to='profiler.associateddevice'),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='known_ips',
            field=models.ManyToManyField(blank=True, related_name='technical_profiles', to='profiler.associatedip'),
        ),
    ]
