# Generated by Django 5.0.1 on 2024-02-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0010_alter_technicalprofile_known_devices_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tactics',
            new_name='Tactic',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='known_devices',
        ),
    ]
