# Generated by Django 5.0.1 on 2024-02-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0011_rename_tactics_tactic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
