# Generated by Django 5.0.1 on 2024-02-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0012_alter_tactic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='tactic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.tactic'),
        ),
    ]
