# Generated by Django 5.0.1 on 2024-02-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0013_technique_tactic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
