# Generated by Django 5.0.1 on 2024-02-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0014_alter_technique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercriminal',
            name='d_o_b',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='cyber_criminal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.cybercriminal'),
        ),
    ]
