# Generated by Django 5.0.1 on 2024-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0015_alter_cybercriminal_d_o_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercriminal',
            name='name',
            field=models.CharField(help_text='Middle name/s should be entered in full and not be represented by an initial', max_length=255),
        ),
        migrations.DeleteModel(
            name='PsychologicalProfile',
        ),
    ]
