# Generated by Django 5.0.1 on 2024-02-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0016_alter_cybercriminal_name_delete_psychologicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggression_level', models.IntegerField(help_text='Aggression level on a scale of 1-10')),
                ('risk_taking_level', models.IntegerField(help_text='Risk-taking level on a scale of 1-10')),
                ('cyber_criminal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.cybercriminal')),
            ],
            options={
                'verbose_name_plural': 'Psychological Profiles',
            },
        ),
    ]
