# Generated by Django 5.0.1 on 2024-02-08 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0017_psychologicalprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalprofile',
            name='known_phrases',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='procedures',
        ),
        migrations.AddField(
            model_name='technicalprofile',
            name='manifesto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologicalprofile',
            name='aggression_level',
            field=models.IntegerField(help_text='Aggression level on a scale of 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='psychologicalprofile',
            name='risk_taking_level',
            field=models.IntegerField(help_text='Risk-taking level on a scale of 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='hacker_classification',
            field=models.CharField(choices=[('BH', 'Black Hat'), ('GH', 'Grey Hat'), ('SK', 'Script Kiddie'), ('HA', 'Hacktivist'), ('SS', 'State-Sponsored'), ('CT,Cyber-Terrorist', 'Cyber Terrorist'), ('MI', 'Malicious Insider')], default='BH', max_length=20),
        ),
        migrations.DeleteModel(
            name='KnownPhrase',
        ),
    ]
