# Generated by Django 5.0.1 on 2024-02-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0018_remove_technicalprofile_known_phrases_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.RenameField(
            model_name='previousconviction',
            old_name='conviction',
            new_name='crime',
        ),
        migrations.RenameField(
            model_name='previousconviction',
            old_name='date',
            new_name='date_of_conviction',
        ),
        migrations.RemoveField(
            model_name='associatedip',
            name='location',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='known_ips',
        ),
        migrations.AddField(
            model_name='associatedip',
            name='cyber_criminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_ips', to='profiler.cybercriminal'),
        ),
    ]
