# Generated by Django 5.0.1 on 2024-02-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0019_delete_procedure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviousConviction',
        ),
    ]
