# Generated by Django 5.0.1 on 2024-02-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0020_delete_previousconviction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associateddevice',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='associateddevice',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='associated_devices',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='associated_ips',
        ),
        migrations.AddField(
            model_name='associateddevice',
            name='cyber_criminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_devices', to='profiler.cybercriminal'),
        ),
    ]
