# Generated by Django 5.0.1 on 2024-02-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0021_remove_associateddevice_device_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='cyber_criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='profiler.cybercriminal'),
        ),
    ]
