# Generated by Django 5.0.1 on 2024-02-11 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0022_alter_alias_cyber_criminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologicalprofile',
            name='cyber_criminal',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='cyber_criminal',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='tactics',
        ),
        migrations.RemoveField(
            model_name='technicalprofile',
            name='techniques',
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='aggression_level',
            field=models.IntegerField(default=5, help_text='Aggression level on a scale of 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='eye_color',
            field=models.CharField(default='Brown', max_length=255),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='hacker_classification',
            field=models.CharField(choices=[('BH', 'Black Hat'), ('GH', 'Grey Hat'), ('SK', 'Script Kiddie'), ('HA', 'Hacktivist'), ('SS', 'State-Sponsored'), ('CT,Cyber-Terrorist', 'Cyber Terrorist'), ('MI', 'Malicious Insider')], default='BH', max_length=20),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='hair_color',
            field=models.CharField(default='Black', max_length=255),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='height',
            field=models.PositiveIntegerField(default=170, help_text='Height in centimeters'),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='manifesto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='risk_taking_level',
            field=models.IntegerField(default=5, help_text='Risk-taking level on a scale of 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='tactics',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.tactic'),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='criminal_profiles', to='profiler.technique'),
        ),
        migrations.AddField(
            model_name='cybercriminal',
            name='weight',
            field=models.PositiveIntegerField(default=70, help_text='Weight in kilograms'),
        ),
        migrations.DeleteModel(
            name='PhysicalProfile',
        ),
        migrations.DeleteModel(
            name='PsychologicalProfile',
        ),
        migrations.DeleteModel(
            name='TechnicalProfile',
        ),
    ]
