# Generated by Django 5.0.1 on 2024-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0023_remove_psychologicalprofile_cyber_criminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybercriminal',
            name='eye_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cybercriminal',
            name='hair_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cybercriminal',
            name='height',
            field=models.PositiveIntegerField(help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='cybercriminal',
            name='weight',
            field=models.PositiveIntegerField(help_text='Weight in kilograms', null=True),
        ),
    ]
