# Generated by Django 5.0.1 on 2024-02-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0025_cybercriminal_investigator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cybercriminal',
            options={'ordering': ['investigator', 'name'], 'verbose_name_plural': 'Cyber Criminals'},
        ),
        migrations.AlterUniqueTogether(
            name='technique',
            unique_together={('name', 'tactic')},
        ),
    ]
