# Generated by Django 5.0.1 on 2024-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0027_alter_cybercriminal_d_o_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
