# Generated by Django 5.0.1 on 2024-02-21 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0029_alter_cybercriminal_last_known_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ['name'], 'verbose_name_plural': 'Techniques'},
        ),
        migrations.CreateModel(
            name='CyberCriminalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matched_criminals', models.ManyToManyField(blank=True, related_name='matches', to='profiler.cybercriminal')),
                ('techniques', models.ManyToManyField(blank=True, related_name='matches', to='profiler.technique')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['made_by'],
            },
        ),
    ]
