# Generated by Django 5.0.1 on 2024-02-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0030_alter_technique_options_cybercriminalmatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cybercriminalmatch',
            options={'ordering': ['made_by'], 'verbose_name_plural': 'Cyber Criminal Matches'},
        ),
    ]
