# Generated by Django 5.0.1 on 2024-02-21 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0031_alter_cybercriminalmatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercriminalmatch',
            name='matched_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
